print("Welcome to Sara's Madlib experience.  Enjoy the story!")
wordNoun = input("Choose a noun: ")
wordAdjct = input("Choose an adjective: ")
wordVerbp = input ("Choose a past-tense verb: ")
wordVerbing = input ("Choose a verb ending in -ing: ")
wordAdverb = input ("Choose an adverb [ex: 'wildly']: ")
wordAdverbb = input ("Choose another adverb: ")
wordPlace = input ("Choose a place: ")
print("Once upon a time, there was a man",(wordVerbing),"his dog.  As he strolled past",(wordPlace),", he and his dog discovered a",(wordNoun),"on the side of the road.  The man's dog sniffed the",(wordNoun),(wordAdverb),", before licking it.  The",(wordAdjct),"man yelled",(wordAdverbb),"and ran with his dog back to their home, where the man",(wordVerbp),"for the rest of the day.")